Update aaps-ci.yml

diff --git a/.github/workflows/aaps-ci.yml b/.github/workflows/aaps-ci.yml
--- a/.github/workflows/aaps-ci.yml
+++ b/.github/workflows/aaps-ci.yml
@@ -55,31 +55,30 @@ jobs:
           echo "GDRIVE_OAUTH2=${{ secrets.GDRIVE_OAUTH2 }}" >> $GITHUB_ENV
 
       - name: Check Secrets
-        run: |
-          echo "🔍 Checking required secrets..."
-          MISSING=0
+  if: ${{ github.event.inputs.buildVariant == 'fullRelease' }}
+  run: |
+    echo "🔍 Checking required secrets..."
+    MISSING=0
 
-          check_secret() {
-            if [ -z "$1" ]; then
-              echo "❌ Missing secret: $2"
-              MISSING=1
-            fi
-          }
+    check_secret() {
+      if [ -z "$1" ]; then
+        echo "❌ Missing secret: $2"
+        MISSING=1
+      fi
+    }
 
-          # Check secrets
-          check_secret "$GDRIVE_OAUTH2" "GDRIVE_OAUTH2"
-          
-          check_secret "$KEYSTORE_BASE64" "KEYSTORE_BASE64"
-          check_secret "$KEYSTORE_PASSWORD" "KEYSTORE_PASSWORD"
-          check_secret "$KEY_ALIAS" "KEY_ALIAS"
-          check_secret "$KEY_PASSWORD" "KEY_PASSWORD"
+    # Check secrets
+    check_secret "$GDRIVE_OAUTH2" "GDRIVE_OAUTH2"
 
-          if [ "$MISSING" -eq 1 ]; then
-            echo "🛑 Missing required secrets. Stopping build."
-            exit 1
-          fi
+    check_secret "$KEYSTORE_BASE64" "KEYSTORE_BASE64"
+    check_secret "$KEYSTORE_PASSWORD" "KEYSTORE_PASSWORD"
+    check_secret "$KEY_ALIAS" "KEY_ALIAS"
+    check_secret "$KEY_PASSWORD" "KEY_PASSWORD"
 
-          echo "✅ All required secrets are present."
+    if [ "$MISSING" -eq 1 ]; then
+      echo "🔴 Missing required secrets. Stopping build."
+      exit 1
+    fi
 
       - name: Decode keystore file
         run: |
